### ISSUE TITLE
[TypeScript] Unable to use a plugin with typescript

### ISSUE THREAD

**Issue by Losses** [pimterry/loglevel#149] opened 2020-08-07 03:36 UTC
Just doing similar thing to demo code to add a new plugin:

![image](https://user-images.githubusercontent.com/1384036/89606053-a81c9080-d8a1-11ea-8731-1ad45b9e15db.png)

And got:
![image](https://user-images.githubusercontent.com/1384036/89606329-3ee94d00-d8a2-11ea-9dc8-b1838806afdd.png)

Maybe there're some thong wrong with the TypeScript definition

**Comment by pimterry** [comment] 2020-08-10 16:53
You're right, I can reproduce this, and it's incorrect, but I have no idea why it's happening. It's definitely not marked as a read-only property explicitly.

Any suggestions? Happy to take hints or PRs to get this fixed.

**Closed** 2020-08-26 13:22 UTC

**Comment by pimterry** [comment] 2020-08-26 13:27
Ok, I think I know the cause of this. The problem is that TypeScript assumes that `import * as ...` module export properties are always readonly. That's not true in many real environments, but I think it's required by the ES6 spec, and so will be true in native ES6 environments.

Fortunately, this _is_ possible if you're using a default import. That was only supported in TS if you had `esModuleInterop` enabled, but in https://github.com/pimterry/loglevel/commit/dcc07d1c023d31d9008918a512a9fabb6c01252f I've now added a `.default` property on the root object, which makes this possible all the time.

I'll release this at 1.7.0 in a moment. To use it, just change from:

```typescript
import * as log from 'loglevel';
```

to

```typescript
import log from 'loglevel';
```

Both are supported in general, but to make the types happy when assigning to `methodFactory` in TypeScript, the latter must be used.

**Comment by ELeigh91** [comment] 2022-02-16 17:03
Worked for me using _"allowUmdGlobalAccess": true_ in the _tsconfig.json_
