### ISSUE TITLE
Only `log.info()` messages are output in `catch()` when the level is set to `info`

### ISSUE THREAD

**Issue by tukusejssirs** [pimterry/loglevel#157] opened 2021-01-26 12:01 UTC
I set the log level to `info`. I `try()` executing a command and `catch()` its output. In `catch()`, I’d like to output some messages based on the log level. However, only `info` messages are output.

Note that when I set the log level to `trace`, besides `info` messages, `debug` messages are output too.

IMHO, all messages up to the set level should be output.

```js
log.setLevel('info')

catch (error) {
	log.trace('trace')
	log.debug('debug')
	log.info('info')
	log.warn('warn')
	log.error('error')
}
```

**Comment by pimterry** [comment] 2021-01-26 14:52
Can you provide an example to reproduce this issue? Which version of loglevel are you using, in what environment?

Otherwise as far as I can tell this already works correctly, and this is well-tested & in widespread use in all sorts of places. Testing your code in a node REPL for example:

```javascript
> const log = require('loglevel')
undefined
> log.setLevel('info')
undefined
> try {
...     throw new Error();
... } catch (error) {
... 	log.trace('trace')
... 	log.debug('debug')
... 	log.info('info')
... 	log.warn('warn')
... 	log.error('error')
... }
info
warn
error
```

As expected - info, warn & error all log, and trace & debug are excluded.

Can you share more details about your setup, so I can reproduce the behaviour you're describing myself?

**Comment by tukusejssirs** [comment] 2021-01-26 16:45
FYI, I installed `loglevel` 1.7.1 via `npm` on Fedora 31 x86_64 (Workstation) and on CentOS 8 (non-Stream, minimal server).

However, now I can’t reproduce the behaviour. However, I am sure it didn’t work in my case (even with the MWE). It always worked with `info` level, but not with `warn` level.

Sorry I opened an issue I can’t reproduce anymore. :disappointed:

**Comment by pimterry** [comment] 2021-01-27 11:28
Fair enough, no worries!

I'm going to close this for now since there's nothing really I can do to investigate, but if you or anybody else manages to reproduce this then do let me know, I'm very happy to look into it further.

**Closed by pimterry** 2021-01-27 11:28 UTC
