### ISSUE TITLE
Incompatible with Jest

### ISSUE THREAD

**Issue by linnik** [pimterry/loglevel#85] opened 2015-11-24 06:07 UTC
Hi.
I'm trying to test my project with [Jest](https://facebook.github.io/jest/), and encountered a problem to get it working with `loglevel`. If i try to test any .js file with `require('loglevel')` in it, i get `SyntaxError: Unexpected identifier`.
Can you look into it?

```
// fetchCurrentUser.js
var log = require('loglevel');

function fetchCurrentUser() {
}

module.exports = fetchCurrentUser;
```
```
// __tests__/fetchCurrentUser-test.js
jest.dontMock('../fetchCurrentUser.js');

describe('fetchCurrentUser', function() {
  it('calls into $.ajax with the correct params', function() {
    var fetchCurrentUser = require('../fetchCurrentUser');

});
```
```
// package.json
"devDependencies": {
  "jest-cli": "*"
},
"scripts": {
  "test": "jest"
},
```

**Comment by pimterry** [comment] 2015-11-24 12:55
To start with, you have a syntax error in your test. You're missing the closing bracket for the it() (or the describe, arguably). It should be:

```javascript
jest.dontMock('../fetchCurrentUser.js');

describe('fetchCurrentUser', function() {
  it('calls into $.ajax with the correct params', function() {
    var fetchCurrentUser = require('../fetchCurrentUser');
  }); // <-- This is missing in your example
});
```

Even with that fixed though, you're totally right, Jest complains about a syntax error. I've done some digging and I'm pretty sure this is a Jest bug. Specifically, you can reproduce it by trying to require a file that contains only:

```javascript
module.exports = console.error.bind(console);
```

I think Jest tries to do some quite clever inspection to work some stuff out, but it can't understand some of the (admittedly somewhat fiddly) things that loglevel has to do to make sure logging works seamlessly everywhere.

I'm not going to be able to fix this in loglevel. I'm going to talk to the Jest team and take a look at fixing it deep within Jest itself, but that's going to be a) difficult, b) slow (and you'll have to wait for a release) and c) it might not work.

There's a discussion from lots of other library authors at https://github.com/facebook/jest/issues/90, suggesting Jest has lots of these kind of problems. Conclusion seems to be that you just can't ask Jest to automock things like this, and you'll have to workaround it instead.

Sorry about that. Good luck! I'll leave this open until I either actually get a fix into Jest, or discover that's going to be impractical.

**Comment by mattlo** [comment] 2016-01-16 01:10
@linnik @pimterry Disable mocking for it so it won't swap it out with a jest-interpreted version. I got `loglevel` working with React tests after configuring the following in **package.json**:

```
"jest": {
  ...
  "unmockedModulePathPatterns": [
    ...
    "<rootDir>/node_modules/loglevel"
  ]
}
```

I hope this helps!

**Comment by pimterry** [comment] 2016-03-16 12:30
I have looked into this a bit, but I'm not too au fait with Jest and lots of other people who are more comfortable with it haven't solved this for their libraries either, so I'm going to close this, and not delve any deeper.

I've given the Jest team a report for the minimal repro to play with (https://github.com/facebook/jest/issues/804); if they fix that then great, loglevel will probably start working, if not then the workaround for now is to add loglevel to your unmockedModulePathPatterns as above.

**Closed by pimterry** 2016-03-16 12:30 UTC

**Comment by artemv** [comment] 2018-09-19 09:59
In my case configuring `unmockedModulePathPatterns` didn't help, probably because jest' automocking is not relevant anymore as it's not enabled by default. What helped is a hack from https://github.com/facebook/jest/issues/687#issuecomment-370080590: 
```
var log = require('loglevel');

log.info = console.log;
log.debug = console.log;
log.trace = console.log;
```
