### ISSUE TITLE
Debug level is not showing in console

### ISSUE THREAD

**Issue by asasine** [pimterry/loglevel#111] opened 2017-08-07 00:52 UTC
As the title states, calls to `log.debug` do not print results to the console. The following script _index.js_ was run with `node index.js`:

```
var log = require('loglevel');

log.setLevel(log.levels.TRACE);

log.error('error');
log.warn('warn')
log.info('info');
log.debug('debug');
log.trace('trace');
```

and the following was displayed on the console:

```
error
warn
info
Trace: trace
    at Object.<anonymous> (/some/random/directory/index.js:9:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

As the output shows, the `DEBUG` level is skipped.

I am using loglevel v1.4.1 with Node.js 8.2.1 and npm 5.3.0 on macOS 10.12.6.

**Comment by pimterry** [comment] 2017-08-08 17:22
Yes, this is currently being discussed over here: https://github.com/pimterry/loglevel/issues/64#issuecomment-319423251. V8 seems to have quietly made console.debug do nothing, which breaks this. The current plan is to just map `log.debug` to `console.log` in future - would that work for you?

**Comment by asasine** [comment] 2017-08-08 17:27
Yes this would work for my needs. In the future of this package, I share the sentiment of @olegstepura that there should exist all 6 logging levels.

**Comment by kutuluk** [comment] 2017-08-11 13:52
![debug](https://user-images.githubusercontent.com/5966195/29215897-dfbc4b8e-7ebd-11e7-881f-5caaf5abab41.jpg)

**Comment by nicocrm** [comment] 2017-09-03 20:10
+1 for mapping to console.log.... it's annoying not having a debug log level.  Any plan for updating that soon?

**Comment by pimterry** [comment] 2017-09-11 22:26
This should now be fixed, released in 1.5.0.

`log.debug` now uses `console.log` under the hood, so will work in Chrome versions that make `console.debug` a noop. Thanks for the report, let me know if you have any further trouble!

**Closed by pimterry** 2017-09-11 22:26 UTC

**Comment by Trikolon** [comment] 2017-09-13 09:47
I don't understand why this change is required for Chrome. The latest stable version of Chrome shows `console.debug` statements if you enable all log levels in the console as shown by @kutuluk . Am I missing something here?

**Comment by pimterry** [comment] 2017-09-13 09:55
@Trikolon not having these messages appear by default is somewhat annoying and confusing for loglevel users, and the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Console) say:

> Console.debug()
> An alias for log() - starting with Chromium 58 this method is a no-op on Chromium browsers.

In addition, it's no longer listed in the Node docs for `console` at all: https://nodejs.org/api/console.html

You're right that you can change the log levels as an effective a workaround. At the moment though it looks like `console.debug` is being steadily killed off, there's zero downside I can see to using `console.log` under the hood instead, and it makes loglevel work more intuitively for Chrome users right now.

**Comment by Trikolon** [comment] 2017-09-13 10:55
That makes sense. Thanks for the explanation!

**Comment by MichelSimonot** [comment] 2018-08-17 13:59
@pimterry It's much more annoying to have them logged at the wrong level.

The MDN docs have probably been updated since you quoted them, but `console.debug` is not a noop.

![screen shot 2018-08-17 at 9 56 53 am](https://user-images.githubusercontent.com/1817346/44269945-f8f1d500-a203-11e8-916f-6ab9d52c979a.png)

Please don't try to fix a "problem" that isn't yours by changing expected behaviour.
