### ISSUE TITLE
Would you consider deprecating in favor of Roarr?

### ISSUE THREAD

**Issue by gajus** [pimterry/loglevel#170] opened 2021-08-11 22:04 UTC
Hi @pimterry 

I wouldn't suggest this if the project was actively maintained (judging only by lack of recent commits), but I was wondering if you are planning to deprecate this project and if so would you suggest [Roarr](https://github.com/gajus/roarr).

The documentation for Roarr includes my motivation for maintaining yet another logger, and based on the API of loglevel, I feel like we have overlapping goals.

Would love to accept you as a contributor if you have ideas about how logging should evolve and how that fits into Roarr.

**Comment by pimterry** [comment] 2021-08-12 10:09
Hi @gajus! Thanks for getting in touch. This library isn't unmaintained though, it's simply 'done'. It's very widely used, and there's still occasional questions and discussion in the issues that get handled, and small changes every few months, but yes nothing major is changing now.

I hadn't seen Roarr, looks interesting. I'm not sure it's targeting the same audience as this library though. Loglevel is designed to be a maximally compatible 100% reliable but very simple tiny logger, just a more reliable & more configurable console.log. It looks like Roarr is much more fully featured, for users who want structured logging, remote transports, and so on. That's all great, and very useful in larger application logging, but often you just need nice very simple logging for a quick script or CLI tool, or a browser logger that plays nicely in IE, or a tiny zero-dependency logger to get configurable levels without appearing in console.log stacktrace anywhere. Tiny & simple is a feature.

That's the use case that loglevel is covering - it's _not_ a do-everything application logging framework, by design.

If you're keen though, I'm happy to add an 'Alternatives' section in the readme somewhere, maybe just after 'Features'. I'd be happy to look at a PR that says something like "Loglevel is designed for quick & simple logging that works everywhere in a tiny package, but this might not be the right tool for advanced use cases where you want a full logging framework. Here's some alternatives that might be worth a look: ...", and then references a selection of different alternatives, with a little information on when each one is useful, if you want to put one together.

In the meantime I'll close this, since this definitely isn't being deprecated, but feel free to open that PR to expand the docs if you like.

**Closed by pimterry** 2021-08-12 10:09 UTC

**Comment by gajus** [comment] 2021-08-12 14:29
Thank you for a thorough response.

I am thinking of creating a directory of all logging solutions for JavaScript. Will definitely include `loglevel`.
